CREATE TABLE BOOK(
    ID NUMBER(10),
    TITLE VARCHAR2(50),
    AUTHOR VARCHAR2(50)
);

ALTER TABLE BOOK ADD CONSTRAINT BOOK_ID_PK PRIMARY_KEY(ID);

CREATE SEQUENCE BOOK_SEQ NOCACHE;

SELECT * FROM BOOK;