spring.application.name=spring-myweb


server.port=8282

# database option
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:mysql://localhost:3306/spring?serverTimezone=Asia/Seoul
spring.datasource.username=spring
spring.datasource.password=spring

# SQL mapper Location
mybatis.mapper-locations=classpath:/mapper/**/*.xml
# package name as alias
mybatis.type-aliases-package=com.sgn08062.spring_myweb.command