SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;

-- 특정 컬러만 확인하고 싶으면
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES;


-- 별칭 as, as 없이 띄어쓰기로 가능, ""로 칼럼명 띄어쓰기 가능
SELECT FIRST_NAME AS 이름, SALARY * 12 "1년 연봉", SALARY 급여 FROM EMPLOYEES;

-- 문자열을 붙일때
SELECT FIRST_NAME || ' ' || LAST_NAME || '님의 급여는' || SALARY AS 급여 FROM EMPLOYEES;
SELECT FIRST_NAME || ' ' || LAST_NAME || '''s salary is $' || SALARY AS "Employee Details" FROM employees;

-- DISTINCT 키워드 완전히 동일한 행에 대해서 중복 제거
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES;

-- ROWID는 데이터가 저장되는 주소값
-- ROWNUM은 조회되는 순서에 일련번호를 붙임
SELECT FIRST_NAME, SALARY, ROWID, ROWNUM FROM EMPLOYEES;
