--WHERE절
SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Steven';
SELECT * FROM EMPLOYEES WHERE SALARY >= 10000;

--BETWEEN ~ AND 이상 이하
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 10000 AND 12000;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '05/01/01' AND '05/12/31';

-- IN
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (50, 60, 70);
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('ST_CLERK', 'IT_PROG');

--LIKE ( %-무엇이든 들어올 수 있음, _ - 자릿수)
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '03%' -- 03년 입사자
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%03'; -- 03일 입사자
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%03%';

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '_a%'; -- 두번째 글자가 a인 데이터

-- IS NULL ( = NULL은 먹히지 않는다)
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT = NULL; -- 아무것도 안나옴
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL; 
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;

-- AND, OR, NOT
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR SALARY >= 5000;
SELECT * FROM EMPLOYEES WHERE (JOB_ID = 'IT_PROG' OR JOB_ID = 'FI_MGR') AND SALARY >= 5000;

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID NOT IN (50, 60);

-- ORDER BY 셀렉트 질의 맨 마지막에 들어간다.
SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;

-- ORDER 벌에는 별칭이 사용 가능
SELECT FIRST_NAME, SALARY*12 ANNSAL FROM EMPLOYEES ORDER BY ANNSAL DESC;