--집합연산자
--UNION 합집합, 중복X
--UNION ALL 합집합, 중복O
--INTERSECT 교집합
--MINUS 차집합
SELECT * FROM EMPLOYEES;

-- 주의할 점
-- 컬럼의 개수와 각 컬럼의 데이터 형식이 일치해야 합치기 가능
SELECT FIRST_NAME, EMAIL FROM EMPLOYEES WHERE HIRE_DATE LIKE '04%'
MINUS--INTERSECT--UNION ALL--UNION
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID=20;

-- 가짜데이터를 만들어서 사용할 때
SELECT 'HONG', 20 FROM DUAL
UNION ALL
SELECT 'LEE', 30 FROM DUAL
UNION ALL
SELECT 'CHOI', 23 FROM DUAL;

-- 분석함수
-- SQLD 시험에서 무조건 등장
SELECT FIRST_NAME, SALARY,
    RANK() OVER(ORDER BY SALARY DESC) SAL_RANK,
    DENSE_RANK() OVER(ORDER BY SALARY DESC) SAL_DENSE_RANK,
    ROW_NUMBER() OVER(ORDER BY SALARY DESC) SAL_ROW_NUMBER
FROM EMPLOYEES;