--그룹함수
--AVG, SUM, MAX, MIN, COUNT(*), COUNT(컬럼)
SELECT SUM(SALARY), AVG(SALARY), MAX(SALARY), MIN(SALARY), COUNT(SALARY)
FROM EMPLOYEES WHERE JOB_ID LIKE 'SA%';

--MIN, MAX는 날짜타입, 문자에도 적용됨
SELECT MIN(HIRE_DATE), MAX(HIRE_DATE) FROM EMPLOYEES;
SELECT MIN(FIRST_NAME), MAX(FIRST_NAME) FROM EMPLOYEES;
--COUNT() 사용방법 2가지
SELECT COUNT(*), -- 전체 행 수
       COUNT(COMMISSION_PCT) -- NULL이 아닌 데이터의 개수 
FROM EMPLOYEES;

-- 그룹함수를 쓸 때 자주하는 실수 - 일반컬럼, 그룹함수를 같이 사용함
SELECT FIRST_NAME, SUM(SALARY) FROM EMPLOYEES;
-- WINDOW절을 사용하면 일반컬럼 옆에 그룹함수 값을 동시에 붙여서 사용할 수 있음
SELECT FIRST_NAME, 
        SUM(SALARY) OVER(),
        MAX(SALARY) OVER(),
        MIN(SALARY) OVER(),
        AVG(SALARY) OVER()
FROM EMPLOYEES;

-- GROUP BY
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;
-- 그룹함수를 같이 사용 가능
SELECT DEPARTMENT_ID,
       SUM(SALARY),
       AVG(SALARY),
       COUNT(*),
       MAX(SALARY),
       MIN(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;
-- 주의할 점 - 그룹화하지 않은 칼럼을 SELECT절에 바로 넣을 수 없음

-- 2개 이상의 그룹화
SELECT DEPARTMENT_ID, JOB_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPARTMENT_ID;

-- GROUP BY의 조건을 쓰는 절은 WHERE이 아닌 HAVING
-- 평균 급여가 6000이상인 부서만 출력
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) >= 6000;

SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 6000;

-- 샐러리맨이 아닌 사람들의, 직무별 급여 평균이 6000 이상인 데이터, 평균, 합계, 평균 내림차순으로 정렬
SELECT JOB_ID, TRUNC(AVG(SALARY)) 평균, SUM(SALARY)합계
FROM EMPLOYEES
WHERE JOB_ID NOT LIKE 'SA%'
GROUP BY JOB_ID
HAVING AVG(SALARY) >= 6000
ORDER BY 평균 DESC;

-------------------------------------------------------------------------------------
-- ROLLUP
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY), 2), COUNT(*)
FROM EMPLOYEES
GROUP BY ROLLUP(DEPARTMENT_ID)
ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, JOB_ID, ROUND(AVG(SALARY), 2), COUNT(*)
FROM EMPLOYEES
GROUP BY ROLLUP(DEPARTMENT_ID, JOB_ID)
ORDER BY DEPARTMENT_ID, JOB_ID;

-- CUBE = ROLLUP + 서브그룹의 총계까지 추가
SELECT DEPARTMENT_ID, JOB_ID, ROUND(AVG(SALARY), 2), COUNT(*)
FROM EMPLOYEES
GROUP BY CUBE(DEPARTMENT_ID, JOB_ID)
ORDER BY DEPARTMENT_ID;

-- GROUPING - GROUP BY로 생성되었으면 0 반환, ROLLUP OR CUBE로 생성되었으면 1 반환
SELECT DECODE(GROUPING(DEPARTMENT_ID),1, '총계', DEPARTMENT_ID),
       DECODE(GROUPING(JOB_ID), 1, '소계', JOB_ID), 
       SUM(SALARY),
       GROUPING(DEPARTMENT_ID),
       GROUPING(JOB_ID)
FROM EMPLOYEES
GROUP BY ROLLUP(DEPARTMENT_ID,JOB_ID)
ORDER BY DEPARTMENT_ID;



-------------------------------------------------------------------------------
--연습문제
--문제 1.
--사원 테이블에서 JOB_ID별 사원 수, 월급의 평균, 가장빠른 입사일을 구하세요. 
--월급의 평균 순으로 내림차순 정렬하세요.
SELECT JOB_ID, COUNT(*) 사원수, AVG(SALARY) 급여평균, MIN(HIRE_DATE) 최소입사일
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY AVG(SALARY);
--문제 2.
--사원 테이블에서 입사 년도 별 사원 수를 구하세요.
SELECT TO_CHAR(HIRE_DATE, 'YYYY"년"') 입사년도, COUNT(*) 사원수
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'YYYY"년"')
ORDER BY 입사년도;

--문제 3.
--급여가 1000 이상인 사원들의 부서별 평균 급여를 출력하세요. 단 부서 평균 급여가 2000이상인 부서만 출력
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
WHERE SALARY >= 1000
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) >= 2000;
--문제 4.
--사원 테이블에서 commission_pct(커미션) 컬럼이 null이 아닌 사람들의
--department_id(부서별) salary(월급)의 평균, 합계, count를 구합니다.
--조건 1) 월급의 평균은 커미션을 적용시킨 월급입니다.
--조건 2) 평균은 소수 2째 자리에서 절삭 하세요.
SELECT DEPARTMENT_ID, TRUNC(AVG(SALARY + SALARY*COMMISSION_PCT), 2), SUM(SALARY), COUNT(SALARY)
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY DEPARTMENT_ID;
--문제 5.
--부서아이디가 NULL이 아니고, 입사일은 05년도 인 사람들의 부서 급여평균과, 급여합계를 평균기준 내림차순합니다
--조건) 평균이 10000이상인 데이터만
SELECT DEPARTMENT_ID, AVG(SALARY), SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL AND TO_CHAR(TRUNC(HIRE_DATE, 'YEAR'), 'YY') = '05'
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) >= 10000
ORDER BY AVG(SALARY) DESC;
--문제 6.
--직업별 월급합, 총합계를 출력하세요
SELECT DECODE(GROUPING(JOB_ID), 1, '합계', JOB_ID), 
       SUM(SALARY)
FROM EMPLOYEES
GROUP BY ROLLUP(JOB_ID)
ORDER BY JOB_ID;

--문제 7.
--부서별, JOB_ID를 그룹핑 하여 사원수 , 급여 합계를 출력하세요.
--GROUPING() 을 이용하여 소계 합계를 표현하세요
SELECT DECODE(GROUPING(DEPARTMENT_ID), 1, '합계', DEPARTMENT_ID) DEPARTMENT_ID
      ,DECODE(GROUPING(JOB_ID),1,'소계', JOB_ID) JOB_ID
      ,COUNT(*) TOTAL
      ,SUM(SALARY) SUM
FROM EMPLOYEES
GROUP BY ROLLUP(DEPARTMENT_ID, JOB_ID)
ORDER BY SUM;