-- INNER JOIN: 연결할 데이터가 없으면 나오지 않음
SELECT * 
FROM INFO 
INNER JOIN AUTH -- INNER는 생략 가능함
ON INFO.AUTH_ID = AUTH.AUTH_ID;
-- 테이블 엘리어스
SELECT *
FROM INFO I
JOIN AUTH A
ON I.AUTH_ID = A.AUTH_ID;
-- SELECT 구문의 선택 - 동일한 컬럼명이 있는 경우에 참조테이블을 지정해야 한다.
SELECT ID,
       TITLE,
       I.AUTH_ID,
       NAME
FROM INFO I
JOIN AUTH A
ON I.AUTH_ID = A.AUTH_ID;
-- USING ON 구문을 쓸수도 있음
SELECT *
FROM INFO I
JOIN AUTH A
USING (AUTH_ID);


-- LEFT OUTER JOIN
SELECT * 
FROM INFO 
LEFT OUTER JOIN AUTH  -- OUTER 생략 가능
ON INFO.AUTH_ID = AUTH.AUTH_ID;
-- RIGHT OUTER JOIN
SELECT *
FROM INFO I
RIGHT OUTER JOIN AUTH A -- OUTER 생략 가능
ON I.AUTH_ID = A.AUTH_ID;
-- FULL JOIN
SELECT *
FROM INFO I
FULL JOIN AUTH A
ON I.AUTH_ID = A.AUTH_ID;

-- CROSS JOIN - 카타시안 프로덕트
SELECT *
FROM INFO CROSS JOIN AUTH;
---------------------------------------------------
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;

-- 조인은 여러 개 붙일 수도 있다
SELECT * 
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
WHERE EMPLOYEE_ID = 100;

------------------------------------------------
-- 오라클에서 사용하는 오라클 조인문법
-- 테이블을 FROM절에 ,로 적음
-- WHERE 에서 조인 조건을 적음
SELECT *
FROM INFO I, AUTH A
WHERE I.AUTH_ID = A.AUTH_ID;

-- LEFT JOIN
SELECT *
FROM INFO I, AUTH A
WHERE I.AUTH_ID = A.AUTH_ID(+);
-- RIGHT JOIN
SELECT *
FROM INFO I, AUTH A
WHERE I.AUTH_ID(+) = A.AUTH_ID;

-- CROSS JOIN
SELECT *
FROM INFO, AUTH;

-- SELF JOIN
SELECT E1.FIRST_NAME 사원명, E2.FIRST_NAME 매니저명
FROM EMPLOYEES E1
LEFT JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID;

-- NON EQUALS JOIN
-- 두 테이블을 조인할 때 = 연산자 대신 >, >=, <>, BETWEEN AND 등을 이용해서 조인을 하는 방법
-- 보통 키관계가 없는 컬럼들을 붙여서 쓸 때 사용할 수 있다
-- 크로스조인을 기반으로 동작함
SELECT *
FROM EMPLOYEES
CROSS JOIN JOBS;

-- MIN SALARY의 한 행에 대해서 SALARY가 큰 사람들을 출력
SELECT *
FROM EMPLOYEES E
JOIN JOBS J
ON E.SALARY > J.MIN_SALARY;
SELECT * FROM JOBS;
SELECT *
FROM EMPLOYEES E
JOIN JOBS J
ON E.SALARY >= J.MIN_SALARY AND E.SALARY <= J.MAX_SALARY;
--------------------------------------------------------------------------------
--문제 1.
--EMPLOYEES, DEPARTMENTS 테이블을 엘리어스를 이용해서 조인해보세요.
--조건) 각각 INNER, LEFT, RIGHT 조인 해보세요.
SELECT *
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT *
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT *
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT *
FROM EMPLOYEES E
FULL OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
--문제 2.
--EMPLOYEES, DEPARTMENTS 테이블을 INNER JOIN하세요.
--조건)employee_id가 200인 사람의 이름, department_id를 출력하세요
--조건)이름 컬럼은 first_name과 last_name을 합쳐서 출력합니다
SELECT FIRST_NAME || LAST_NAME, E.DEPARTMENT_ID
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.EMPLOYEE_ID=200;

SELECT * FROM EMPLOYEES;
SELECT * FROM JOBS;
--문제 3.
--EMPLOYEES, JOBS테이블을 INNER JOIN하세요
--조건) 모든 사원의 이름과 직무아이디, 직무 타이틀을 출력하고, 이름 기준으로 오름차순 정렬
--HINT) 어떤 컬럼으로 서로 연결되 있는지 확인
SELECT FIRST_NAME || LAST_NAME 이름, E.JOB_ID, JOB_TITLE
FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
ORDER BY 이름;
--문제 4.
--JOBS테이블과 JOB_HISTORY테이블을 조인하세요.
--조건) JOS_HISTORY테이블에 알맞는 부서명도 출력하세요.
--힌트) 조인 2번
SELECT * FROM JOBS;
SELECT * FROM JOB_HISTORY;
SELECT * FROM DEPARTMENTS;
SELECT DEPARTMENT_NAME
FROM JOBS J
JOIN JOB_HISTORY JH ON J.JOB_ID=JH.JOB_ID
JOIN DEPARTMENTS D ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID;
--문제 5.
--Steven King의 부서명을 출력하세요.
SELECT FIRST_NAME||' '||LAST_NAME 이름, DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE FIRST_NAME || ' ' || LAST_NAME = 'Steven King';
--문제 6.
--EMPLOYEES 테이블과 DEPARTMENTS 테이블을 Cartesian Product(Cross join)처리하세요
SELECT *
FROM EMPLOYEES
CROSS JOIN DEPARTMENTS;
---------------------------------------------------------------------------------------
--문제 7.
--EMPLOYEES 테이블과 DEPARTMENTS 테이블의 부서번호를 조인하고 SA_MAN 사원만의 사원번호, 이름, 
--급여, 부서명, 근무지를 출력하세요. (Alias를 사용)
SELECT * FROM EMPLOYEES;
SELECT EMPLOYEE_ID 사원번호, FIRST_NAME||' '||LAST_NAME 이름, SALARY 급여, DEPARTMENT_NAME 부서명, CITY 근무지
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE E.JOB_ID = 'SA_MAN';
--문제 8.
--employees, jobs 테이블을 조인 지정하고 job_title이 'Stock Manager', 'Stock Clerk'인 직원 정보만
--출력하세요.
SELECT *
FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE J.JOB_TITLE IN ('Stock Manage', 'Stock Clerk');
--문제 9.
--departments 테이블에서 직원이 없는 부서를 찾아 출력하세요.
SELECT * 
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
WHERE EMPLOYEE_ID IS NULL;
--문제 10. 
--join을 이용해서 사원의 이름과 그 사원의 매니저 이름을 출력하세요
--힌트) EMPLOYEES 테이블과 EMPLOYEES 테이블을 조인하세요.
SELECT E1.FIRST_NAME 사원명, E2.FIRST_NAME 매니저명
FROM EMPLOYEES E1
LEFT JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID;
--문제 11. 
--EMPLOYEES 테이블에서 left join하여 관리자(매니저)와, 매니저의 이름, 매니저의 급여 까지 출력하세요
--조건) 매니저 아이디가 없는 사람은 배제하고 급여는 역순으로 출력하세요
SELECT CONCAT(E1.FIRST_NAME, E1.LAST_NAME) 사원명, E1.MANAGER_ID 매니저_아이디, 
       CONCAT(E2.FIRST_NAME, E2.LAST_NAME) 매니저명, E2.SALARY 매니저_급여
FROM EMPLOYEES E1
LEFT JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID
WHERE E1.MANAGER_ID IS NOT NULL
ORDER BY E2.SALARY DESC;