-- 서브쿼리: SELECT절 안에 SELECT가 들어가는 유형
-- 단일행서브쿼리 - SELECT한 서브쿼리 결과가 1행인 서브쿼리
-- 서브쿼리 문법은 반드시 ()로 묶어준다. 연산자보다 오른쪽에 위치한다

-- 낸시보다 급여 많이 받은 사람은 누구냐?????????
--> 1.낸시 급여 확인 -> 2. 낸시 급여보다 큰 사람 찾음
SELECT CONCAT(FIRST_NAME, LAST_NAME), SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM EMPLOYEES
                WHERE FIRST_NAME = 'Nancy');
                
-- 직원 아이디가 103인 사람과 동일한 직무를 가진 사람
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE JOB_ID = ( SELECT JOB_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 103);

-- 스티븐 킹이랑 동일한 부서를 가진 사람들
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES
                       WHERE FIRST_NAME = 'Steven' AND LAST_NAME = 'King');


--------------------------------------------------------------------------------
-- 다중행 서브쿼리 IN, ANY, ALL
-- IN - 정확히 일치하는 데이터
-- ANY - 최솟값보다 큰 OR 최대값보다 작은
-- ALL - 최대값보다 큰 OR 최솟값보다 작은

-- 데이비드의 급여
SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'David';
--4800보다 큰 사람들
SELECT *
FROM EMPLOYEES
WHERE SALARY >= ANY (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'David');
-- 9500보다 작은 사람들
SELECT *
FROM EMPLOYEES
WHERE SALARY <= ANY (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'David');

-- 9500보다 큰 사람들
SELECT *
FROM EMPLOYEES
WHERE SALARY >= ALL (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'David');

-- 4800보다 작은 사람들
SELECT *
FROM EMPLOYEES
WHERE SALARY <= ALL (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'David');

-- 정확히 일치하는 데이터
SELECT *
FROM EMPLOYEES
WHERE SALARY IN (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'David');

---------------------------------------------------------------------------------
-- 스칼라 쿼리 (서브쿼리절이 select 구문에 들어간 형태)
-- LEFT JOIN을 대체할 수 있음 (조인된 테이블의 1개 컬럼을 가져올 때 유리함)
SELECT FIRST_NAME,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT FIRST_NAME,
       (SELECT DEPARTMENT_NAME FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID) AS DEPARTMENT_NAME
FROM EMPLOYEES E;
-- 각 직원의 부서명, 직무이름을 가지고 올 것임
SELECT FIRST_NAME, 
       (SELECT DEPARTMENT_NAME FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID) AS D_NAME,
       (SELECT JOB_TITLE FROM JOBS J WHERE E.JOB_ID = J.JOB_ID) AS J_TITLE
FROM EMPLOYEES E;

-- 테이블 엘리어스
SELECT E.*, 
       (SELECT DEPARTMENT_NAME FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID) AS D_NAME,
       (SELECT JOB_TITLE FROM JOBS J WHERE E.JOB_ID = J.JOB_ID) AS J_TITLE
FROM EMPLOYEES E;

SELECT
    D.DEPARTMENT_NAME,
    (SELECT AVG(E.SALARY)
     FROM EMPLOYEES E
     WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) AVG_SALARY
FROM
    DEPARTMENTS D;

SELECT * FROM DEPARTMENTS;

-----------------------------------------------------------------------------
-- 인라인뷰 (FROM에 들어가는 서브쿼리)
-- 인라인뷰에서 만든 가상 칼럼들에 대해서 연속적으로 조회해 나갈 때 사용함

-- ROWNUM은 조회된 순서에 번호가 붙음. ORDER BY하면서 순서가 뒤바뀜
SELECT ROWNUM,
       FIRST_NAME,
       SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

-- 해결하기 위해 인라인 뷰를 한다
SELECT ROWNUM, FIRST_NAME, SALARY
FROM (SELECT FIRST_NAME, SALARY
      FROM EMPLOYEES
      ORDER BY SALARY DESC)
WHERE ROWNUM BETWEEN 11 AND 20; -- ROWNUM은 순서 붙이기라서 1번부터만 가능. 11번부터 시작해서 안나옴

-- 한번 더 인라인 뷰를 중첩시켜 해결한다.
SELECT RNUM, FIRST_NAME, SALARY
FROM(SELECT ROWNUM RNUM, FIRST_NAME, SALARY
     FROM (SELECT FIRST_NAME, SALARY
           FROM EMPLOYEES
           ORDER BY SALARY DESC)
    )
WHERE RNUM BETWEEN 11 AND 20;

-- 예시
SELECT A.*
FROM (
    SELECT FIRST_NAME||' '||LAST_NAME 이름, 
       TRUNC((SYSDATE-HIRE_DATE)/365) 근속년수, 
       TO_CHAR(HIRE_DATE, 'YYYY"년" MM"월" DD"일"') 입사일,
       NVL(COMMISSION_PCT, 0) 커미션
    FROM EMPLOYEES
    ORDER BY 근속년수 DESC) A
WHERE MOD(근속년수, 5) = 0;