--문제 1.
--1) EMPLOYEES 테이블에서 모든 사원들의 평균급여보다 높은 사원들을 데이터를 출력 하세요 ( AVG(컬럼) 사용)
SELECT *
FROM EMPLOYEES
WHERE SALARY >= (SELECT AVG(SALARY) FROM EMPLOYEES);
--2) EMPLOYEES 테이블에서 모든 사원들의 평균급여보다 높은 사원들을 수를 출력하세요
SELECT COUNT(*)
FROM EMPLOYEES
WHERE SALARY >= (SELECT AVG(SALARY) FROM EMPLOYEES);
--3) EMPLOYEES 테이블에서 job_id가 IT_PFOG인 사원들의 평균급여보다 높은 사원들을 데이터를 출력하세요.
SELECT *
FROM EMPLOYEES
WHERE SALARY >= (SELECT AVG(SALARY) FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG');

--문제 2.
--DEPARTMENTS테이블에서 manager_id가 100인 사람의 department_id(부서아이디) 와
--EMPLOYEES테이블에서 department_id(부서아이디) 가 일치하는 모든 사원의 정보를 검색하세요.
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID 
                       FROM DEPARTMENTS 
                       WHERE MANAGER_ID=100);

--문제 3.
--EMPLOYEES테이블에서 “Pat”의 manager_id보다 높은 manager_id를 갖는 모든 사원의 데이터를 출력하세요
SELECT *
FROM EMPLOYEES E1
WHERE E1.MANAGER_ID > (SELECT MANAGER_ID
                       FROM EMPLOYEES E2
                       WHERE E2.FIRST_NAME = 'Pat');
--EMPLOYEES테이블에서 “James”(2명)들의 manager_id와 같은 모든 사원의 데이터를 출력하세요.
SELECT *
FROM EMPLOYEES E1
WHERE E1.MANAGER_ID IN (SELECT MANAGER_ID
                        FROM EMPLOYEES E2
                        WHERE E2.FIRST_NAME = 'James');
--Steven과 동일한 부서에 있는 사람들을 출력해주세요.
SELECT *
FROM EMPLOYEES E1
WHERE E1.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                        FROM EMPLOYEES E2
                        WHERE E2.FIRST_NAME = 'Steven');
--Steven의 급여보다 많은 급여를 받는 사람들은 출력하세요.
SELECT *
FROM EMPLOYEES E1
WHERE E1.SALARY > ANY(SELECT SALARY
                   FROM EMPLOYEES E2
                   WHERE E2.FIRST_NAME = 'Steven');
                   
--문제 4.
--EMPLOYEES테이블 DEPARTMENTS테이블을 left 조인하세요
--조건) 직원아이디, 이름(성, 이름), 부서아이디, 부서명 만 출력합니다.
--조건) 직원아이디 기준 오름차순 정렬
SELECT EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME NAME, E.DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY EMPLOYEE_ID;

--문제 5.
--문제 4의 결과를 (스칼라 쿼리)로 동일하게 조회하세요
SELECT EMPLOYEE_ID, 
       FIRST_NAME||' '||LAST_NAME NAME, 
       DEPARTMENT_ID,
       (SELECT DEPARTMENT_NAME
        FROM DEPARTMENTS
        WHERE DEPARTMENT_ID = E.DEPARTMENT_ID) DEPARTMENT_NAME
FROM EMPLOYEES E
ORDER BY EMPLOYEE_ID;

--문제 6.
--DEPARTMENTS테이블 LOCATIONS테이블을 left 조인하세요
--조건) 부서아이디, 부서이름, 주소(STREET_ADDRESS), 시티(CITY) 만 출력합니다
--조건) 부서아이디 기준 오름차순 정렬
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, STREET_ADDRESS, CITY
FROM DEPARTMENTS D
LEFT JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
ORDER BY DEPARTMENT_ID;
--문제 7.
--문제 6의 결과를 (스칼라 쿼리)로 동일하게 조회하세요
SELECT
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    (SELECT L.STREET_ADDRESS
     FROM LOCATIONS L
     WHERE L.LOCATION_ID = D.LOCATION_ID) AS STREET_ADDRESS,
    (SELECT L.CITY
     FROM LOCATIONS L
     WHERE L.LOCATION_ID = D.LOCATION_ID) AS CITY
FROM DEPARTMENTS D;
    
--문제 8.
--LOCATIONS테이블 COUNTRIES테이블을 스칼라 쿼리로 조회하세요.
--조건) 로케이션아이디, 주소, 시티, country_id, country_name 만 출력합니다
--조건) country_name기준 오름차순 정렬
SELECT LOCATION_ID, 
       STREET_ADDRESS, 
       CITY, 
       COUNTRY_ID,
       (SELECT COUNTRY_NAME FROM COUNTRIES
        WHERE COUNTRY_ID = L.COUNTRY_ID) COUNTRY_NAME
FROM LOCATIONS L
ORDER BY COUNTRY_NAME;

--문제 9.
--EMPLOYEES테이블 에서 first_name기준으로 내림차순 정렬하고, 41~50번째 데이터의 행 번호, 이름을 출력하세요
SELECT RNUM, FIRST_NAME
FROM (SELECT ROWNUM RNUM, FIRST_NAME
      FROM (SELECT FIRST_NAME
            FROM EMPLOYEES
            ORDER BY FIRST_NAME DESC)
      )
WHERE RNUM BETWEEN 41 AND 50;

--문제 11.
--COMMITSSION을 적용한 급여를 새로운 컬럼으로 만들고, 이 데이터에서 10000보다 큰 사람들을 뽑아 보세요. (인라인뷰를 쓰면 됩니다)
SELECT SALARY
FROM (SELECT SALARY + SALARY*NVL(COMMISSION_PCT, 0) SALARY
      FROM EMPLOYEES)
WHERE SALARY > 10000;

--문제 12.
--조인의 최적화
--SELECT CONCAT(FIRST_NAME, LAST_NAME) AS NAME,
--       D.DEPARTMENT_ID
--FROM EMPLOYEES E
--JOIN DEPARTMENTS D
--ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
--WHERE EMPLOYEE_ID = 200;
SELECT CONCAT(FIRST_NAME, LAST_NAME) NAME,
       (SELECT DEPARTMENT_ID
        FROM DEPARTMENTS
        WHERE DEPARTMENT_ID = E.DEPARTMENT_ID) DEPARETMENT_ID
FROM EMPLOYEES E
WHERE EMPLOYEE_ID=200;
--부서아이디가 200인 데이터를 인라인뷰로 조회한 후에 JOIN을 붙여보세요.
SELECT CONCAT(FIRST_NAME, LAST_NAME) NAME, A.DEPARTMENT_ID
FROM (SELECT *
      FROM EMPLOYEES
      WHERE EMPLOYEE_ID = 200) A
LEFT JOIN DEPARTMENTS D
ON A.DEPARTMENT_ID = D.DEPARTMENT_ID;
--문제13
--EMPLOYEES테이블, DEPARTMENTS 테이블을 left조인하여, 입사일 오름차순 기준으로 10-20번째 데이터만 출력합니다.
--조건) rownum을 적용하여 번호, 직원아이디, 이름, 입사일, 부서이름 을 출력합니다.
--조건) hire_date를 기준으로 오름차순 정렬 되어야 합니다. rownum이 망가지면 안되요.
SELECT RNUM, EMPLOYEE_ID, NAME, HIRE_DATE, DEPARTMENT_NAME
FROM (SELECT ROWNUM RNUM, EMPLOYEE_ID, NAME, HIRE_DATE, DEPARTMENT_NAME
      FROM (SELECT EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME NAME, HIRE_DATE, DEPARTMENT_NAME
            FROM EMPLOYEES E
            LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
            ORDER BY HIRE_DATE)
     )
WHERE RNUM BETWEEN 10 AND 20;
--문제14
--SA_MAN 사원의 급여 내림차순 기준으로 ROWNUM을 붙여주세요.
--조건) SA_MAN 사원들의 ROWNUM, 이름, 급여, 부서아이디, 부서명을 출력하세요.
SELECT ROWNUM RNUM, 
       A.*,
       (SELECT DEPARTMENT_NAME 
        FROM DEPARTMENTS 
        WHERE DEPARTMENT_ID = A.DEPARTMENT_ID) DEPARTMENT_NAME
FROM(SELECT FIRST_NAME||' '||LAST_NAME NAME, SALARY, DEPARTMENT_ID
     FROM EMPLOYEES
     WHERE JOB_ID='SA_MAN'
     ORDER BY SALARY DESC) A
;


--문제15
--DEPARTMENTS테이블에서 각 부서의 부서명, 매니저아이디, 부서에 속한 인원수 를 출력하세요.
--조건) 인원수 기준 내림차순 정렬하세요.
--조건) 사람이 없는 부서는 출력하지 뽑지 않습니다.
--힌트) 부서의 인원수 먼저 구한다. 이 테이블을 조인한다.
SELECT D.DEPARTMENT_ID, DEPARTMENT_NAME, D.MANAGER_ID MANAGER_ID, EM_COUNT 사원수
FROM ( -- 각 부서의 인원수 구함
      SELECT DEPARTMENT_ID, COUNT(*) EM_COUNT
      FROM EMPLOYEES
      GROUP BY DEPARTMENT_ID) E
      -- E 테이블과 DEPARTMENTS 테이블을 조인
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY EM_COUNT DESC;


--문제16
--부서에 모든 컬럼, 주소, 우편번호, 부서별 평균 연봉을 구해서 출력하세요.
--조건) 부서별 평균이 없으면 0으로 출력하세요
SELECT
    D.*,
    L.STREET_ADDRESS,
    L.POSTAL_CODE,
    NVL(TRUNC((SELECT AVG(E.SALARY)
               FROM EMPLOYEES E
               WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID)), 0) AS "부서별_평균_연봉"
FROM
    DEPARTMENTS D
JOIN
    LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;