-- 트랜잭션 (직업의 논리적인 단위)
-- DML문에서 트랜잭션을 수행할 수 있음
-- DCL, DML문은 자동으로 COMMIT이 적용됨

-- 오토커밋의 상태
SHOW AUTOCOMMIT;

-- 보통 오토커밋은 비활성화한다
SET AUTOCOMMIT OFF;

-- SAVEPOINT 트랜잭션의 시점을 기록할 수 있음
SELECT * FROM DEPTS;

DELETE FROM DEPTS WHERE DEPARTMENT_ID = 10;
SAVEPOINT DEL10;

DELETE FROM DEPTS WHERE DEPARTMENT_ID = 20;
SAVEPOINT DEL20;

DELETE FROM DEPTS WHERE DEPARTMENT_ID = 30;
SAVEPOINT DEL30;

ROLLBACK TO DEL10;
ROLLBACK TO DEL20;

SELECT * FROM DEPTS;