-- DDL문장
-- CREATE, ALTER, DROP, TRUNCATE
DROP TABLE DEPTS;

CREATE TABLE DEPTS(
    DEPT_NO NUMBER(2), -- 정수 2자리
    DEPT_NAME VARCHAR2(30), -- 30바이트(한글 15, 영어 30)
    DEPT_YN CHAR(1), -- 고정문자열 1BYTE
    DEPT_DATE DATE,
    DEPT_BONUS NUMBER(10, 2), --전체 유효자리는 10자리, 소수점 2자리까지 사용할 수 있음
    DEPT_CONTENT LONG
);

DESC DEPTS;
INSERT INTO DEPTS VALUES(99, 'HELLO', 'Y', SYSDATE, 3.14, 'HELLO WORLD');
INSERT INTO DEPTS VALUES(100, 'HELLO', 'Y', SYSDATE, 3.1224, 'HELLO WORLD');
INSERT INTO DEPTS VALUES(1, 'HELLO', '가', SYSDATE, 3.14, 'HELLO WORLD');

CREATE TABLE DEPT2(
    DEPT_NO NUMBER(3),
    DEPT_NAME VARCHAR(15),
    LOCA_NUMBER NUMBER(3),
    DEPT_GENDER CHAR(1),
    REG_DATE DATE,
    DEPT_BONUS NUMBER(5,2)
);

ALTER TABLE DEPT2 RENAME COLUMN DEPT_BONUS TO DEPT_CMT;

ALTER TABLE DEPT2 ADD (DEPT_ADDR VARCHAR(15));

DROP TABLE DEPT2;