-- 제약조건
-- NOT NULL = NULL을 허용하지 않음
-- UNIQUE KEY = 중복 X, NULL허용
-- PRIMARY KEY = NOT NULL + UNIQUE KEY

-- 열 레벨로 정의
-- CONSTRAINT와 제약조건명은 생략 가능함
CREATE TABLE DEPTS (
    DEPT_NO NUMBER(2)       CONSTRAINT DEPTS_DEPT_NO_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(30)  CONSTRAINT DEPTS_DEPT_NAME_NN NOT NULL,
    DEPT_DATE DATE          DEFAULT SYSDATE, -- 기본값 지정 (재약X)
    DEPT_PHONE VARCHAR2(30) CONSTRAINT DEPTS_DEPT_PHONE_UK UNIQUE,
    DEPT_GENDER CHAR(1)     CONSTRAINT DEPTS_DEPT_GENDER_CK CHECK( DEPT_GENDER IN ('F','M')),
    LOCA_ID NUMBER(4)       CONSTRAINT DEPTS_LOCA_ID_FK REFERENCES LOCATIONS(LOCATION_ID)
);

INSERT INTO DEPTS( DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES( 1, NULL, '010-...', 'F', 1700); -- NOT NULL

INSERT INTO DEPTS( DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES( 1, 'HONG', '010-...', 'X', 1700); -- CHECK 제약조건

INSERT INTO DEPTS( DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES( 1, 'HONG', '010-...', 'F', 100); -- 무결성 제약조건

INSERT INTO DEPTS( DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES( 1, 'HONG', '010-...', 'F', 1700); -- OK

INSERT INTO DEPTS( DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES( 2, 'HONG', '010-...', 'F', 1700); -- UNIQUE 제약조건

DROP TABLE DEPTS;


-- 테이블 레벨 정의
CREATE TABLE DEPTS (
    DEPT_NO NUMBER(2),
    DEPT_NAME VARCHAR2(30) NOT NULL, -- NOT NULL은 열 레벨로 지정함
    DEPT_DATE DATE          DEFAULT SYSDATE, -- 기본값 지정 (재약X)
    DEPT_PHONE VARCHAR2(30),
    DEPT_GENDER CHAR(1),
    LOCA_ID NUMBER(4),
    CONSTRAINT DEPTS_DEPT_NO_PK PRIMARY KEY (DEPT_NO, DEPT_NAME),
    CONSTRAINT DEPTS_DEPT_PHONE_UK UNIQUE (DEPT_PHONE),
    CONSTRAINT DEPTS_DEPT_GENDER_CK CHECK (DEPT_GENDER IN('F','M')),
    CONSTRAINT DEPTS_LOCA_ID_FK FOREIGN KEY (LOCA_ID) REFERENCES LOCATIONS(LOCATION_ID)
);


-- 제약조건의 추가 삭제
CREATE TABLE DEPTS (
    DEPT_NO NUMBER(2),
    DEPT_NAME VARCHAR2(30) NOT NULL,
    DEPT_DATE DATE          DEFAULT SYSDATE, -- 기본값 지정 (재약X)
    DEPT_PHONE VARCHAR2(30),
    DEPT_GENDER CHAR(1),
    LOCA_ID NUMBER(4)
);
-- PK 추가
ALTER TABLE DEPTS ADD CONSTRAINT DEPT_NO_PK PRIMARY KEY (DEPT_NO);
-- UK
ALTER TABLE DEPTS ADD CONSTRAINT DEPT_PHONE_UK UNIQUE (DEPT_PHONE);
-- CHECK
ALTER TABLE DEPTS ADD CONSTRAINT DEPT_GENDER_CK CHECK (DEPT_GENDER IN ('M','F'));
--FK
ALTER TABLE DEPTS ADD CONSTRAINT DEPT_LOCATION_FK FOREIGN KEY (LOCA_ID) REFERENCES LOCATIONS(LOCATION_ID);
-- NOT NULL은 MODIFY 문장으로 수정이 된다.
ALTER TABLE DEPTS MODIFY DEPT_PHONE VARCHAR2(30) NOT NULL;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEPTS';

-- 제약조건의 삭제
ALTER TABLE DEPTS DROP CONSTRAINT DEPT_GENDER_CK;


DROP TABLE DEPTS;

SELECT * FROM DEPTS;