-- 계정생성
CREATE USER USER01 IDENTIFIED BY USER01;
-- 권한 부여
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO USER01;
-- 이 계정이 사용하는 테이블스페이스(데이터가 저장되는 물리적 공간)을 연결
ALTER USER USER01 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
ALTER USER USER01 DEFAULT TABLESPACE MYDBF QUOTA UNLIMITED ON MYDBF;
-- 보기탭 > DBA
-- 테이블 스페이스 직접 만드는 방법 검색

-- 권한 회수
REVOKE CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE FROM USER01;
-- 계정 삭제
DROP USER USER01 CASCADE; -- 계정과 연결된 디비스키마를 전부 삭제하면서 유저 삭제


------------------------------------------------------------------------------
-- 롤을 이용해서 권한 부여
CREATE USER USER01 IDENTIFIED BY USER01;
GRANT CONNECT, RESOURCE TO USER01; -- CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE의 집합
ALTER USER USER01 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
DROP USER USER01;
